### ISSUE TITLE
Template for proposing a session at the unconference

### ISSUE THREAD

**Issue by SusanneWenzel** [DKRZ-AIM/HAI-HI-unconference-2023#1]
***** This should go to the readme ****** 

# Future Challenges: an Unconference 
Helmholtz AI and Helmholtz Imaging Conferences 2023

👉 For the conferences full programme visit [Helmholtz AI Conference 2023](https://helmholtzai-conference2023.de/) and 
[Helmholtz Imaging Conference 2023](https://events.hifis.net/event/573/)

The idea of an unconference is to form a programme together 
🤝 Please post ideas for sessions as [issues](https://github.com/DKRZ-AIM/HAI-HI-unconference-2023/issues). You need to have a GitHub account in order to do so.

💡  Feel free to start a rough description of your idea as a new git issue and discuss with potential collaborators. 
📜 **Rule 1:** One issue per potential unconference session
🍒 Comment on existing issues if you have any thoughts or questions about it. You can also mention how you could contribute or anything else relevant to the idea.

📜 **Rule 2:** At the end there should be an abstract addressing the following items.
* **Title**
* **Description**, pointing out, e.g.
    * Question to be addressed
    * Task to be solved
    * Final outcome or even product, e.g., a blog post, a draft for a white paper, an outline for a software prototype, a list of rules to follow, a list of answers to specific questions
* **Organizer(s)**
in best case also name a representative. Don't forget to add contact information, i.e. email or github ID
* **Speakers**, if applicable
In case the format foresees an introduction, short talks etc.
* **Format**
E.g., talks followed by open discussion, hackathon like format, world café, etc. 
You can find a list of common unconference formats [here](http://unconference.net/methods-2/). But at the end its up to the organizers
* **Timeframe**
Specify the time you foresee for this session, e.g., 30min, 1h, ..., up to 3h
* **Number of participants**
Define the minimal number of participants you need to work on the specified task. 
Is there a limit to the number of people who attend this session?

📜 Rule 3: Please make sure that your session ideas are understandable to everyone. We come from different fields. Use as little jargon as possible. 💁

_**to be discussed**_
_We will review proposals in a two-stage process. On May 15 no more new issues are accepted. Until May 29 the existing proposals for sessions can still be discussed, merged, closed, or finalized. We will decide on the final program based on what we have after this second deadline._

If you run into any problems with this process, please contact the program chairs **[tbd](mailto:tbd) and/or [tbd](mailto:tbd)**.

Many thanks for inspiration and help in setting this up to the team of [deRSE23 unconference breakouts](https://github.com/DE-RSE/un-deRSE23-breakouts), Heidi Seibold, Robert Speck, Guido Juckeland

* Typical unconference [formats](http://unconference.net/methods-2/)
* Helpfull [tips](https://unconference.net/unconferencing-how-to-prepare-to-attend-an-unconference-2/)

****** This will go to the issue template ***********
# Title
# Description
_pointing out, e.g._
    * _Question to be addressed_
    * _Task to be solved_
    * _Final outcome or even product, e.g., a blog post, a draft for a white paper, an outline for a software prototype, a list of rules to follow, a list of answers to specific questions_
# Organizational
## Organizer(s)
_In best case also name a representative. Don't forget to add contact information, i.e. email or github ID_
## Speakers
_if applicable_
_In case the format foresees an introduction, short talks etc._
## Format
_E.g., talks followed by open discussion, hackathon like format, world café, etc. 
You can find a list of common unconference formats [here](http://unconference.net/methods-2/). But at the end its up to the organizers_
## Timeframe
_Specify the time you foresee for this session, e.g., 15min, 30min, 1h, ..., up to_ **_3h tbd_**
## Number of participants
_Define the minimal number of participants you need to work on the specified task. 
Is there a limit to the number of people who attend this session?_

**Comment by HeidiSeibold** [comment]
This can be done even more automated: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by SusanneWenzel** [comment]
Perfect! Good to know. Then let's discuss the content and then I'll transfer it to the settings

**Comment by helenehoffmann** [comment]
- Why two names for organizers? From my point of view, one is enough.
- I think I would rather say: Title, Description, Desired Outcome instead of abstract
- I think a timeslot of 15 minutes is too short, maybe start with 30 min.

I think most points are fine. These are just some minor additions ;)

**Comment by SusanneWenzel** [comment]
1. then organizer plus representative (I'd like to have a backup, but I'm also ok with one)
2. ok, also though about description instead
3. we said 15 min in our discussion, but I'm fine with 30 min, too. What about the max length?

**Comment by helenehoffmann** [comment]
3 h is OK I think, only if we have a lot of contributions we might need to shorten some.

**Comment by ikurecic** [comment]
Notes from the meeting:

- Should include information to issue authors that they'll be expected to give a <1' pitch at the start of the event.
- Should note to issue authors they will need to write a summary/conclusion of their session by the end of it (it would allow us to track successes, but also give a chance to people who didn't attend to potentially join the new team's plans).

**Comment by SusanneWenzel** [comment]
Readme and template for issues are setup. Thank you for the discussion
