### ISSUE TITLE
Reproducibility in ML

### ISSUE THREAD

**Issue by psteinb** [DKRZ-AIM/HAI-HI-unconference-2023#5]
# Title

Reproducibility in ML for the masses: recipes, methods, stepping stones

# Description

In this session, we'd like to collect best practices and stepping stones on how to keep your ML model or pipeline reproducible. What concrete steps need to be taken, to have reproducible predictions of a trained model.

There will be a teaser presentation to give attendants a head start on challenges. We would love to crowd-source further ideas then in order to compile a short guide for practitioners (if time permits). We hope with this, that a diverse set of aspects on reproducibility in ML become more widely known in our community. Ultimately, this leads to wider uptake of such methods in both Helmholtz.AI and Helmholtz Imaging. 

# Organizational

## Organizer(s)

* Peter Steinbach, @psteinb
* volunteers?

## Speakers

* Peter Steinbach, Introduction to Reproducibility

## Format

Depending on the attendance, the seminar could take the form:
1. Welcome (2')
2. Introduction to Reproducibility (10-13')
3. Group Work: Share Reproducibility Failures and Successes (20')
4. Recap: Reproducibility Failures and Successes (5')
5. Group Work: Reproducibility Hints  (20')
6. Conclusion and Goodbye (10')

Total: 75-90'
Goal: Compile an electronic document collecting Reproducibility Failures and Successes as well as a guide for practitioners how to ensure reproducibility. 

## Timeframe

1-1.5h ( would be great if this would not be in parallel with #4 )

## Number of participants

1-30

**Comment by HeidiSeibold** [comment]
Awesome idea! But I guess you knew I would like it @psteinb 😜 
Are you still looking for co-organisers?

@sophiajw this might be interesting for you as well.

**Comment by sophiajw** [comment]
Thanks for tagging me @HeidiSeibold!
Indeed, sounds pretty cool! Let me know if I can contribute anything before the conference.

**Comment by SusanneWenzel** [comment]
@psteinb Would you need a screen? We have a few available, but possibly not for each session. Flipchart will be available

**Comment by psteinb** [comment]
I can live without. Give it to others that need it.On 13. Jun 2023, at 11:11, Susanne Wenzel ***@***.***> wrote:﻿
@psteinb Would you need a screen? We have a few available, but possibly not for each session. Flipchart will be available

**Comment by SusanneWenzel** [comment]
Thank you, noted. Let us please talk later today how to arrange unconf sessions #5 and #4 and your talk in session 7

**Comment by psteinb** [comment]
We are in room one. We just split up in 4 teams. Each team is asked to share ideas and experiences about the following 3 questions:

- one example where you have suffered from published results not being reproducible?
- one example where you have benefited from reproducible published work?
- what do you do to ensure that your published work is reproducible?

We reconvene at 3:35pm

**Comment by FabianIsensee** [comment]
FYI this session was split into 4 subgroups. Ours is sitting here
https://maps.app.goo.gl/JJ3PmWevuitvuHwD8

**Comment by SusanneWenzel** [comment]
@psteinb if possible, please make a note here on the (rough) number of participants. Also don't forget to make a note here about the outcome of the session and, if applicable, future plans that came out of this session.

**Comment by FabianIsensee** [comment]
Wrap up here
https://maps.app.goo.gl/E1E2ErNMQmmw5LJH6

**Comment by psteinb** [comment]
### Short summary of the workshop

- throughout the session approx. 20 people participated on average
- all details of the summary are available [in the notepad](https://notes.desy.de/nyLScku8QKW0PkZ-apTv5A?view#summary)
	- repro considered hard, but essential (should be resourced and rewarded by KPIs)
	- very nuanced topic which depends on domain (from bitwise reproducibility to "want to end up in the same ballpark")
	- many frustrated by published results that are NOT reproducible
	- many motivated and want to exchange experiences and ideas

- collected email addresses and will start small seminar series on the topic

**Comment by IsraMekki0** [comment]
For those interested in **Quicksetup-ai** (the template we discussed). Here it is:
- [Documentation](https://quicksetup-ai.readthedocs.io/en/latest/)
- [Repo](https://github.com/HelmholtzAI-Consultants-Munich/Quicksetup-ai)

**Comment by psteinb** [comment]
For those who watch this issue, I coordially invite everyone to continue the discussion (and planning) [here](https://mattermost.hzdr.de/signup_user_complete/?id=gwwhx9jy1jdc3g47i64n47ysxe&md=link&sbr=su). I will also send out an invitation by mail to those who shared their address with me.
